#!/usr/bin/env python3
"""Emit a VitePress theme layer from DTCG tokens — replacing hand-copied literals.

The problem, measured
---------------------
A docs theme typically re-states its design system's colours by hand. In this repository
`docs/.vitepress/theme/werkstoff.css` shares 28 distinct hex literals with
`tools/design-tokens/tokens.css` and makes **zero** `var()` references back to it.

Where those literals live is the part worth getting right, and a first pass got it wrong:
only **four** sit in the framework's own `--vp-*` namespace. The real duplication is a
parallel **`--wk-*` copy of the entire token set**, 30 declarations deep. Looking only at
`--vp-*` found one mapping and missed the drift vector entirely, which is why `--prefix`
exists.

What this emits
---------------
The same assignments as references: `--wk-bg: var(--bg)`. One source, and the theme layer
becomes derived output rather than a second original. Against this repo it turns 26
literals into references and leaves 2 orphans — values with no token, no card, no grade
and no recorded contrast — for a human.

How the mapping is proposed — and why that is not the thing I argued against
---------------------------------------------------------------------------
`--adopt` derives a proposed mapping from an existing hand-written theme by matching each
`--vp-*` literal against the token set. That is value-matching, which the provenance graph
refuses to do — the difference is what the result is used for. There, a matched value
became an asserted *edge*, a fact later phases trusted. Here it is a **proposal a human
reviews**, and every ambiguity is reported rather than resolved:

* one literal matching several tokens is reported with all candidates and mapped to none;
* a literal matching no token is reported as an **orphan** — a value living outside the
  system with no card, no grade and no recorded contrast.

Usage:
    emit_vitepress.py --tokens tokens.json --adopt existing-theme.css [--out FILE]
    emit_vitepress.py --selftest
Exit: 0 emitted, 1 unusable input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import emit_css  # noqa: E402

DECL = re.compile(r"(--[\w-]+)\s*:\s*([^;{}]+);")
HEX = re.compile(r"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")


def norm(value: str) -> str:
    v = value.strip().lower()
    if len(v) == 4 and v.startswith("#"):
        v = "#" + "".join(c * 2 for c in v[1:])
    return v


def token_literals(doc: dict) -> dict[str, list[str]]:
    """hex -> the css names of every token holding it. A list, because collisions are real."""
    out: dict[str, list[str]] = defaultdict(list)
    for path, token in emit_css.walk(doc):
        value = token.get("$value")
        name = emit_css.css_name(path, token)
        if isinstance(value, dict) and value.get("hex"):
            out[norm(value["hex"])].append(name)
    return out


def adopt(doc: dict, theme_css: str, prefix: str = "--vp-"
          ) -> tuple[list[tuple[str, str]], list[str], list[str]]:
    """(mappings, ambiguous, orphans) for every prefixed literal in an existing theme.

    The prefix is a parameter because the duplication is not always in the framework's
    namespace. This repo's docs theme keeps a parallel `--wk-*` copy of the ENTIRE token
    set — 30 declarations — and only four `--vp-*` literals. Hardcoding `--vp-` would
    have reported one mapping and missed the actual drift vector.
    """
    literals = token_literals(doc)
    mappings: list[tuple[str, str]] = []
    ambiguous: list[str] = []
    orphans: list[str] = []
    seen: set[str] = set()

    for name, raw in DECL.findall(theme_css):
        if not name.startswith(prefix) or name in seen:
            continue
        value = norm(raw)
        if not HEX.match(value):
            continue
        seen.add(name)
        candidates = literals.get(value, [])
        if len(candidates) == 1:
            mappings.append((name, candidates[0]))
        elif len(candidates) > 1:
            ambiguous.append(f"{name}: {value} matches {', '.join(sorted(candidates))} "
                             f"— mapped to none; a human picks the role")
        else:
            orphans.append(f"{name}: {value} exists in no token — no card, no grade, "
                           f"no recorded contrast")
    return mappings, ambiguous, orphans


def render(mappings: list[tuple[str, str]], ambiguous: list[str], orphans: list[str]) -> str:
    head = [
        "/* Generated by matrize — do not hand-edit.",
        " *",
        " * Every value here is a REFERENCE into the design system's own tokens, so this",
        " * layer cannot drift from them. Regenerate with:",
        " *   python3 plugins/matrize/scripts/emit_vitepress.py \\",
        " *     --tokens <tokens.json> --adopt <this file>",
        " */",
        ":root {",
    ]
    body = [f"  {vp}: var({token});" for vp, token in mappings]
    tail = ["}"]
    notes: list[str] = []
    if ambiguous or orphans:
        notes.append("\n/* NOT mapped — these need a decision, not a formatter:")
        for a in ambiguous:
            notes.append(f" *   ambiguous  {a}")
        for o in orphans:
            notes.append(f" *   orphan     {o}")
        notes.append(" */")
    return "\n".join(head + body + tail + notes) + "\n"


SAMPLE_TOKENS = {
    "color": {
        "accent": {"$type": "color",
                   "$value": {"colorSpace": "srgb", "components": [0.2, 0.54, 0.85],
                              "hex": "#348ad9"},
                   "$extensions": {"com.werkstoff.matrize": {"cssName": "--accent"}}},
        "text": {"$type": "color",
                 "$value": {"colorSpace": "srgb", "components": [0.87, 0.9, 0.92],
                            "hex": "#dfe6ea"},
                 "$extensions": {"com.werkstoff.matrize": {"cssName": "--text"}}},
        "twin": {"$type": "color",
                 "$value": {"colorSpace": "srgb", "components": [0.2, 0.54, 0.85],
                            "hex": "#348ad9"},
                 "$extensions": {"com.werkstoff.matrize": {"cssName": "--twin"}}},
    }
}

SAMPLE_THEME = """
:root {
  --vp-c-text-1: #dfe6ea;
  --vp-c-brand-1: #348ad9;
  --vp-c-mystery: #abcdef;
  --vp-font-family-base: system-ui;
}
"""


def selftest() -> int:
    checks: list[tuple[str, bool]] = []
    mappings, ambiguous, orphans = adopt(SAMPLE_TOKENS, SAMPLE_THEME)

    names = dict(mappings)
    checks.append(("an unambiguous literal becomes a reference",
                   names.get("--vp-c-text-1") == "--text"))
    checks.append(("a literal matching TWO tokens is not silently picked",
                   "--vp-c-brand-1" not in names))
    checks.append(("and it is reported with every candidate",
                   any("--accent" in a and "--twin" in a for a in ambiguous)))
    checks.append(("a literal in no token is reported as an orphan",
                   any("--vp-c-mystery" in o for o in orphans)))
    checks.append(("a non-colour declaration is left alone",
                   "--vp-font-family-base" not in names))
    # The prefix must actually be honoured, or the tool reports the wrong namespace.
    other = adopt({"color": {"a": {"$type": "color", "$value": {"hex": "#111111"},
                   "$extensions": {"com.werkstoff.matrize": {"cssName": "--ink"}}}}},
                  ":root{--wk-ink:#111111;--vp-ink:#111111;}", prefix="--wk-")
    checks.append(("a non-default prefix is honoured",
                   dict(other[0]) == {"--wk-ink": "--ink"}))

    out = render(mappings, ambiguous, orphans)
    checks.append(("output references, never literals",
                   "var(--text)" in out and "#dfe6ea" not in out.split("NOT mapped")[0]))
    checks.append(("unmapped items are carried into the output, not dropped",
                   "ambiguous" in out and "orphan" in out))
    checks.append(("output says it is generated", "do not hand-edit" in out))
    checks.append(("deterministic", render(*adopt(SAMPLE_TOKENS, SAMPLE_THEME)) == out))

    for label, ok in checks:
        print(f"  {label:<52} {'ok' if ok else 'FAIL'}")
    bad = sum(1 for _, ok in checks if not ok)
    print(f"\n{len(checks)} check(s), {bad} failure(s)")
    print("RED" if bad else "GREEN")
    return 1 if bad else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--tokens")
    ap.add_argument("--adopt", help="an existing hand-written theme to derive a mapping from")
    ap.add_argument("--prefix", default="--vp-", help="the duplicated namespace to map")
    ap.add_argument("--out")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if not args.tokens or not args.adopt:
        ap.print_help()
        return 1
    try:
        doc = json.loads(Path(args.tokens).read_text(encoding="utf-8"))
        theme = Path(args.adopt).read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as exc:
        print(f"emit_vitepress.py: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1

    mappings, ambiguous, orphans = adopt(doc, theme, args.prefix)
    text = render(mappings, ambiguous, orphans)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        print(text, end="")
    print(f"\n{len(mappings)} literal(s) became references; "
          f"{len(ambiguous)} ambiguous, {len(orphans)} orphan(s) left for a human",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
