#!/usr/bin/env python3
"""Render docs/prompt-quality-findings.md from analysis/prompt-review/*.json.

Refuses to render when a FAILED-* marker is newer than run.json — that is exactly the
state in which the JSON on disk belongs to an earlier run than the one somebody just
watched fail. When analysis/prompt-review/ holds no run at all (fresh checkout, CI),
the committed document is left untouched and the script exits 0, so
`rrt artifacts --check` compares the committed file against itself.

Usage: build_report.py [--out docs/prompt-quality-findings.md]
Exit: 0 rendered or nothing to render; 1 refused (stale marker or unreadable inputs).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
IN = ROOT / "analysis/prompt-review"
SEV_ORDER = {"blocker": 0, "major": 1, "minor": 2, "nit": 3}
TIERS = ["haiku", "sonnet", "opus", "human"]


def load(name: str):
    p = IN / name
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else None


_CODE_SPAN = re.compile(r"(`+)(.+?)\1")


def escape_angles(text: str) -> str:
    """Escape `<`/`>` outside inline code spans. VitePress hands the page to Vue's template
    compiler, which reads a bare `<domain>` in a finding's prose as an unclosed element and
    fails the whole site build. Inside backticks markdown-it already escapes them."""
    out, pos = [], 0
    for m in _CODE_SPAN.finditer(text):
        out.append(text[pos:m.start()].replace("<", "&lt;").replace(">", "&gt;"))
        out.append(m.group(0))
        pos = m.end()
    out.append(text[pos:].replace("<", "&lt;").replace(">", "&gt;"))
    return "".join(out)


def md_escape(s) -> str:
    return escape_angles(str(s if s is not None else "").replace("|", "\\|").replace("\n", " ").strip())


def loc(f: dict) -> str:
    return f"`{f['file']}`" + (f":{f['line']}" if f.get("line") else "")


def render(run, findings, routing, synth) -> str:
    verified = findings["verified"]
    lint = findings["lint"]
    cal = run["calibration"]
    L = []
    L.append("# Prompt quality of the nine plugins — what a calibrated review measured\n")
    L.append(f"Run `{run['runStamp']}` · rubric `{run['rubricHash'][:12]}` · generated by "
             "`tools/prompt-review/build_report.py` from `analysis/prompt-review/` (do not edit by hand).\n")
    L.append("Every judgement finding below was produced by a sonnet finder that first had to pass a "
             "planted-defect calibration, then survived an adversarial sonnet refuter that re-opened the "
             "file and searched for the quote. Mechanical findings come from "
             "`tools/prompt-review/lint_prompts.py` (25 regex/YAML rules, each sabotage-tested). The rule "
             "ids resolve in "
             "[`docs/plugin-authoring/references/prompt-quality-rubric.md`](plugin-authoring/references/prompt-quality-rubric.md).\n")

    # A run of six consecutive paragraphs: tables are not text blocks for the theme's
    # breather pass (useBreathers.js counts P/UL/OL only, RUN_MIN=6), and a report that is
    # mostly tables would otherwise never receive the long-page treatment the docs audit
    # (test/docs/docs_ux_audit.py, C4) requires of a page this long.
    L.append("## How to read this report\n")
    L.append("Start with section 1. It says how much to trust everything below it: the finder's recall on planted defects, the sealed hold-out it never trained on, and how accurately the router proxy reproduced the known-answer prompts.\n")
    L.append("Section 2 is the verdict per plugin, one row each, written by opus from the verified findings. Read the summary cell before the numbers.\n")
    L.append("Section 3 is cannibalization. Every pair there was picked together by a haiku router for the same user prompt, then judged. A pair marked intended-handoff needs no change.\n")
    L.append("Section 4 lists every verified judgement finding by severity, with the quote the finder cited and the fix the impact lens approved or revised. A warning sign on a fix means applying it as written would make something else worse.\n")
    L.append("Section 5 is the mechanical lint, grouped by rule. These are the findings a script can prove and a script can fix.\n")
    L.append("Sections 6 and 7 are the backlog by model tier and the cross-plugin synthesis. The ten actions at the end of section 7 are the ordered starting list; the appendix shows which batch and angle each finding came from, so silence in a cell can be read for what it is.\n")

    # ---- instrument
    L.append("## 1. The instrument, before the verdict\n")
    L.append("| measure | value | meaning |\n|---|---|---|")
    for r in cal["rounds"]:
        L.append(f"| calibration round {r['round']} | recall {r['recall']:.2f}, weakest angle {r['perAngleMin']:.2f}, "
                 f"{r['falsePositives']} false positive(s) on clean files | target recall ≥ {cal['targets']['recall']}, every angle ≥ {cal['targets']['perAngle']} |")
    L.append(f"| **sealed hold-out recall** | **{run['sealedRecall']:.2f}** | measured once on fixtures the rewriter never saw; floor {cal['targets']['sealedFloor']} |")
    L.append(f"| raw → verified findings | {run['rawCount']} → {run['verifiedCount']} (+{run['extraFindings']} from the critic round) | the refuter's kill rate |")
    if routing:
        L.append(f"| router proxy accuracy | {routing.get('accuracy', 0):.2f} top-1 on {routing.get('knownAnswerCount', 0)} known-answer prompts (top-3 {routing.get('top3', 0)}) | {routing.get('note', '')} |")
    L.append("")
    if cal.get("rewrites"):
        L.append("The finder prompt was rewritten " + str(len(cal["rewrites"])) + " time(s) during calibration:\n")
        for rw in cal["rewrites"]:
            L.append(f"- after round {rw['afterRound']}: {md_escape(rw['changelog'])}")
        L.append("")
    if run.get("sealedMissed"):
        L.append("Sealed defects the frozen finder still missed (the report's blind spots): " + ", ".join(f"`{m}`" for m in run["sealedMissed"]) + ".\n")

    # ---- per plugin
    L.append("## 2. Per-plugin verdicts\n")
    L.append("| plugin | verdict | verified | lint | summary |\n|---|---|---|---|---|")
    for p in sorted(synth["perPlugin"], key=lambda x: x["plugin"]):
        nv = sum(1 for f in verified if f["file"].startswith(f"plugins/{p['plugin']}/"))
        nl = sum(1 for f in lint if f["file"].startswith(f"plugins/{p['plugin']}/"))
        L.append(f"| **{p['plugin']}** | {p['verdict']} | {nv} | {nl} | {md_escape(p['summary'])} |")
    L.append("")

    # ---- collisions
    L.append("## 3. Cannibalization — measured by routing, judged by opus\n")
    if routing and routing.get("judged"):
        L.append(f"{routing.get('note', '')}. Pairs below were picked together by a haiku router for the ambiguous prompts in "
                 "`tools/prompt-review/ambiguous-prompts.json`.\n")
        L.append("| pair | prompts | verdict | winner | rationale | tier |\n|---|---|---|---|---|---|")
        for j in sorted(routing["judged"], key=lambda x: -len(x.get("promptIds", []))):
            L.append(f"| `{j['a']}` ↔ `{j['b']}` | {len(j.get('promptIds', []))} | {j['verdict']} | {md_escape(j.get('winner', ''))} | {md_escape(j['rationale'])} | {j.get('fix_tier', '')} |")
        L.append("")
    else:
        L.append("No collision pairs were judged in this run.\n")
    if routing and routing.get("misrouted"):
        L.append(f"Known-answer prompts the router got wrong ({len(routing['misrouted'])}):\n")
        L.append("| prompt | expected | router picked |\n|---|---|---|")
        for m in routing["misrouted"][:25]:
            L.append(f"| {md_escape(m['text'])} | `{m['expected']}` | `{m.get('got') or '—'}` |")
        if len(routing["misrouted"]) > 25:
            L.append(f"\n…and {len(routing['misrouted']) - 25} more in `analysis/prompt-review/routing.json`.")
        L.append("")

    # ---- findings by severity
    L.append("## 4. Verified findings\n")
    by_sev = Counter(f["severity"] for f in verified)
    by_angle = Counter(f["angle"] for f in verified)
    L.append("Severity: " + ", ".join(f"{k} {by_sev.get(k, 0)}" for k in SEV_ORDER) + ". Angle: " +
             ", ".join(f"{k} {v}" for k, v in by_angle.most_common()) + ".\n")
    for sev in SEV_ORDER:
        fs = sorted((f for f in verified if f["severity"] == sev), key=lambda f: (f["file"], f.get("line") or 0))
        if not fs:
            continue
        L.append(f"### {sev} ({len(fs)})\n")
        L.append("| where | rule | claim | fix | tier |\n|---|---|---|---|---|")
        for f in fs:
            fix = md_escape(f["suggested_fix"])
            if f.get("fixMakesWorse"):
                fix = "⚠ " + fix + (f" (conflicts with `{f['conflictsWithRule']}`)" if f.get("conflictsWithRule") else "")
            L.append(f"| {loc(f)} | `{f['rule_id']}` | {md_escape(f['claim'])} | {fix} | {f['fix_tier']} |")
        L.append("")

    # ---- lint
    L.append("## 5. Mechanical findings (lint)\n")
    by_rule = Counter(f["rule_id"] for f in lint)
    L.append("| rule | count | files |\n|---|---|---|")
    for rid, n in sorted(by_rule.items(), key=lambda kv: (-kv[1], kv[0])):
        files = sorted({f["file"] for f in lint if f["rule_id"] == rid})
        shown = ", ".join(f"`{x}`" for x in files[:4]) + (f" +{len(files) - 4}" if len(files) > 4 else "")
        L.append(f"| `{rid}` | {n} | {shown} |")
    L.append("")

    # ---- backlog by tier
    L.append("## 6. Fix backlog by model tier\n")
    L.append("Each entry names the cheapest model that can apply it without judgement it lacks. "
             "The lint findings are all haiku-tier by construction.\n")
    for tier in TIERS:
        rows = []
        for p in synth["perPlugin"]:
            for b in p["backlog"]:
                if b["fix_tier"] == tier:
                    rows.append((p["plugin"], b))
        if not rows:
            continue
        L.append(f"### {tier} ({len(rows)})\n")
        L.append("| plugin | file | rules | action |\n|---|---|---|---|")
        for plugin, b in sorted(rows, key=lambda r: (SEV_ORDER.get(r[1].get("severity", "minor"), 2), r[0], r[1]["file"])):
            L.append(f"| {plugin} | `{b['file']}` | {', '.join(f'`{r}`' for r in b['rule_ids'])} | {md_escape(b['action'])} |")
        L.append("")

    # ---- cross-plugin (opus prose)
    L.append("## 7. Cross-plugin synthesis\n")
    cross = (synth.get("cross") or "").strip()
    # the opus prose uses H2 headings; nest them under this section
    cross = re.sub(r"^## ", "### ", cross, flags=re.M)
    safe, in_fence = [], False
    for ln in cross.splitlines():
        if ln.strip().startswith("```"):
            in_fence = not in_fence
            safe.append(ln)
        else:
            safe.append(ln if in_fence else escape_angles(ln))
    L.append("\n".join(safe) + "\n")

    # ---- appendix
    L.append("## Appendix — coverage\n")
    tally = defaultdict(Counter)
    for f in verified:
        tally[f.get("batchKey", "?")][f["angle"]] += 1
    angles = ["meaning", "contract", "clarity", "step-logic", "procedure", "cannibalization", "other"]
    L.append("| batch | files | raw | verified | " + " | ".join(angles) + " |\n|---|---|---|---|" + "---|" * len(angles))
    for b in run.get("batches", []):
        t = tally.get(b["key"], Counter())
        L.append(f"| {b['key']} | {b['files']} | {b['raw']} | {b['verified']} | " + " | ".join(str(t.get(a, 0)) for a in angles) + " |")
    L.append("")
    if synth.get("critic") and synth["critic"].get("gaps"):
        L.append("Completeness critic re-ran these cells: " + ", ".join(f"`{g['batchKey']}` × {g['angle']}" for g in synth["critic"]["gaps"]) + ".\n")
    return "\n".join(L)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ROOT / "docs/prompt-quality-findings.md")
    a = ap.parse_args(argv)

    run = load("run.json")
    if run is None:
        print("no analysis/prompt-review/run.json — nothing to render; leaving the committed report untouched")
        return 0
    run_mtime = (IN / "run.json").stat().st_mtime
    stale = [m for m in IN.glob("FAILED-*") if m.stat().st_mtime > run_mtime]
    if stale:
        print(f"REFUSING to render: {len(stale)} FAILED marker(s) newer than run.json — the JSON on disk is from an earlier run: "
              + ", ".join(m.name for m in stale), file=sys.stderr)
        return 1
    findings, routing, synth = load("findings.json"), load("routing.json"), load("synthesis.json")
    if not (findings and synth):
        print("ERROR: run.json present but findings.json/synthesis.json missing", file=sys.stderr)
        return 1
    for name, obj in (("findings", findings), ("routing", routing or {"runStamp": run["runStamp"]}), ("synthesis", synth)):
        if obj.get("runStamp") != run["runStamp"]:
            print(f"ERROR: {name}.json runStamp {obj.get('runStamp')!r} ≠ run.json {run['runStamp']!r}", file=sys.stderr)
            return 1

    text = render(run, findings, routing, synth)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    tmp = a.out.with_suffix(".md.tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, a.out)
    print(f"wrote {a.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
